package com.projectswg.resources;

public enum ServerConnectionStatus {
	CONNECTING,
	CONNECTED,
	BROKEN_PIPE,
	CONNECTION_RESET,
	CONNECTION_REFUSED,
	ADDR_IN_USE,
	OTHER_SIDE_TERMINATED,
	NO_ROUTE_TO_HOST,
	DISCONNECT_UNKNOWN_REASON,
	DISCONNECT_INTERNAL_ERROR,
	DISCONNECT_INVALID_PROTOCOL,
	DISCONNECTED
}
